### ISSUE TITLE
Performance Issue while adding new order or proforma order.

### ISSUE THREAD

**Issue by jasvir99** [GreatDevelopers/LibreHatti#372]
Seems like we are having some perfromance issue in LibreHatti. When we try to add new order, it take very long to open the page. I think number of item fields is the reason behind. Need to decrease them.

**Comment by jasvir99** [comment]
@aseemmittal and @haramrit , please check whether performace has imrpoved or not.

**Comment by aseemmittal** [comment]
On it.

**Comment by aseemmittal** [comment]
The performance has been improved then before for new order.

**Comment by haramrit** [comment]
On 10 January 2015 at 21:34, aseemmittal <notifications@github.com> wrote:
>
> The performance has been improved then before for new order.


The point where it was stuck for most of time was
"" transferring data from code.jquery.com ""
and it was a one time issue.
After that I runs normally, is this a reason for a delay?


-- 
Har Amrit Pal Singh
http://haramritpanesar.wordpress.com/

**Comment by jasvir99** [comment]
I think it's fine.
