### ISSUE TITLE
View registers

### ISSUE THREAD

**Issue by s-monisha** [GreatDevelopers/LibreHatti#463]
In View Registers icon , TItle - Consultanct Share ; OptIon - Consultanct Share  or (http://127.0.0.1:8000/consultancy_funds_report)
In this it has four fields to fill Start date, End date, Lab and Material :
When you select Lab- Mechanical Lab: Field Work , Material is not enter automatically while in others Lab options, 
For example : When you click on Chemistry Lab : Lab Work , material is automatically fill like Testing of Cement Concrete.
It is not in the case of Mechanical Lab: Field Work. Even if we want to enter can't enter in this text field.
![registers](https://cloud.githubusercontent.com/assets/13537847/9766446/8aa1e27c-5736-11e5-907c-ca3810fde7c3.png)

**Comment by jasvir99** [comment]
Because it doesn't have any field work in database. I have only lab work. We just made a category so if required in future, we can use it.
