### ISSUE TITLE
Doxyfile

### ISSUE THREAD

**Issue by s-monisha** [GreatDevelopers/LibreHatti#465]
/LibreHatti/Doxyfile
write -en as eng or eng. or en- , it can be better option to decribe english.
![doxyfile](https://cloud.githubusercontent.com/assets/13537847/9822270/029b0554-58dd-11e5-9af0-3a4e0771b0b9.png)

**Comment by jasvir99** [comment]
This is file is created by doxygen. You are not supposed to change it.
