### ISSUE TITLE
helper.py

### ISSUE THREAD

**Issue by s-monisha** [GreatDevelopers/LibreHatti#475]
/LibreHatti/src/librehatti/reports/helper.
render or reverse or it supposed to be re??
I will send you PR in coming one or two days.
![helper py](https://cloud.githubusercontent.com/assets/13537847/9966191/efd673f0-5e58-11e5-8fbf-89c8b931aacf.png)

**Comment by manpreet9112** [comment]
What should be in place of " re " at import statement and in place of " rid " at comment  ?

**Comment by jasvir99** [comment]
why you think that they are not correct?

**Comment by manpreet9112** [comment]
I just want to  asked that Is it " import register " or "import reverse" ? or " import re " is correct. Because you did not close this issue , If it is correct.

**Comment by jasvir99** [comment]
It is correct. 're' is python module which stands for regular expression.
