### ISSUE TITLE
No Icons in Home Page

### ISSUE THREAD

**Issue by amarjeetkapoor1** [GreatDevelopers/LibreHatti#510]
![screenshot from 2016-09-16 00-23-06](https://cloud.githubusercontent.com/assets/13377588/18577617/71ea3d18-7c08-11e6-9119-76472d25ed52.png)

**Comment by jasvir99** [comment]
Make sure that you have correct STATICFILES_DIRS path.
https://github.com/GreatDevelopers/LibreHatti/blob/master/src/librehatti/settings.py#L60

**Comment by amarjeetkapoor1** [comment]
There was no mention of this step in README. So, I reported it. Plus now I have updated this path as relative path. So, no problem in future.
