### ISSUE TITLE
dirty branch not working....

### ISSUE THREAD

**Issue by singh1114** [GreatDevelopers/LibreHatti#511]
After the installations of all the requirements, Dirty branch is not working printing following error.

django.db.utils.ProgrammingError: (1146, "Table 'libre.voucher_financialsession' doesn't exist")

**Comment by jasvir99** [comment]
Does migrate works fine?

**Comment by singh1114** [comment]
Didn't worked for me.

**Comment by jasvir99** [comment]
At which step does this error show up?

**Comment by singh1114** [comment]
When we use the command 
python manage.py makemigrations

**Comment by singh1114** [comment]
Ok so I was able to run the dirty branch by using the migrate command in django 1.7 and then running the server in django 1.9. This might not be the right way but it worked.

**Comment by jasvir99** [comment]
You are not supposed to do that.
